version: '3'

services:
  youtubefetch:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: "production"
      target: base
    volumes:
      - ./:/usr/src/app/
    container_name: youtubefetch
    ports:
      - '8080:8080'
    env_file:
      - .env